name: veryeasy
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  auto_route_generator: ^10.0.1
  auto_route: ^10.0.1
  cached_network_image: ^3.4.1
  cached_network_svg_image: ^1.2.0
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_app_check: ^0.3.2+4
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  font_awesome_flutter: ^10.8.0
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.1
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  permission_handler: ^11.4.0
  skeletons: ^0.0.3
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  riverpod_annotation: ^2.6.1
  video_player: ^2.9.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  riverpod_generator: ^2.4.13
  riverpod_lint: ^2.6.4

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/png/logo.png" # Ruta a tu icono
  adaptive_icon_background: "#FFFFFF" # Opcional (para Android 8+)
  adaptive_icon_foreground: "assets/img/png/logo.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf # Fuente regular
        - asset: assets/fonts/Roboto-Bold.ttf # Fuente negrita
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf # Fuente cursiva
          style: italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf # Fuente negrita y cursiva
          weight: 700
          style: italic

  assets:
    - assets/img/gif/
    - assets/img/png/
    - assets/img/svg/
    - .env
