name: veryeasy
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  auto_route_generator: ^10.0.1
  auto_route: ^10.0.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_app_check: ^0.3.2+4
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  google_sign_in: ^6.2.2
  url_launcher: ^6.3.1
  riverpod_annotation: ^2.6.1
  video_player: ^2.9.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.8
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  riverpod_generator: ^2.4.13
  riverpod_lint: ^2.6.4

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/gif/
    - assets/img/png/
    - assets/img/svg/
    - .env
